baseURL = 'https://dreamy-mousse-716062.netlify.app/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'BENING ABADI TRANSPORT JOGJA'
  metaDescription = "SEWA MOBIL JOGJA"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"


[taxonomies]
  category= "theme"
  scene = "scenes"
